[package]
name = "server"
version = "0.1.0"
authors = ["vlad20012 <beskvlad@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rocket_contrib = "0.4.2"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
image = "0.22.2"
bmp = "0.5.0"