[package]
name = "odometry"
version = "0.1.0"
authors = ["Artem Mukhin <Artem.Mukhin@jetbrains.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
